import Link from 'next/link';
import {notFound} from 'next/navigation';
import {Badge} from '@/components/ui/badge';
import {Card,CardContent,CardHeader,CardTitle} from '@/components/ui/card';
import {ConvertLeadButton} from '@/components/admin/convert-lead-button';
import {getSupabaseAdmin} from '@/lib/supabase/admin';
import {workflowSession} from '@/lib/crm/workflow-access';
export const dynamic='force-dynamic';
type Overview={openTickets:number;clients:number;activeClients:number;archived:number;unpaidInvoices:number;leads:Array<{id:string;number:number;name:string;email:string;company:string|null;status:string;converted_client_id:string|null}>};
export default async function AdminOverviewPage(){
 const session=await workflowSession('admin');if(!session)notFound();const {data,error}=await getSupabaseAdmin().rpc('admin_overview',{p_actor:session.userId});if(error||!data)throw new Error('Could not load overview.');const overview=data as Overview;
 return <div className="space-y-6"><h1 className="text-2xl font-semibold">Overview</h1>{overview.archived>0&&<div className="rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900 dark:border-amber-900/50 dark:bg-amber-950/30 dark:text-amber-100">{overview.archived} archived projects held for recovery or cleanup. <Link href="/admin/projects?archived=true" className="underline">Review backups and retention</Link>.</div>}<div className="grid gap-4 sm:grid-cols-3">{[{title:'Open tickets',value:overview.openTickets,text:'Awaiting your reply'},{title:'Unpaid invoices',value:overview.unpaidInvoices,text:'Sent with an outstanding balance'},{title:'Clients',value:overview.clients,text:`${overview.activeClients} active`}].map(item=><Card key={item.title}><CardHeader><CardTitle className="text-sm font-medium text-muted-foreground">{item.title}</CardTitle></CardHeader><CardContent><p className="text-3xl font-semibold">{item.value}</p><p className="mt-1 text-xs text-muted-foreground">{item.text}</p></CardContent></Card>)}</div><section className="space-y-3"><h2 className="text-lg font-semibold">Recent leads</h2>{!overview.leads.length?<p className="text-sm text-muted-foreground">No leads yet.</p>:<div className="overflow-x-auto rounded-lg border"><table className="w-full min-w-[550px] text-sm"><thead className="bg-muted/50 text-left"><tr><th className="p-3">Ref</th><th className="p-3">Name</th><th className="p-3">Company</th><th className="p-3">Status</th><th className="p-3" aria-label="Actions"/></tr></thead><tbody>{overview.leads.map(lead=><tr key={lead.id} className="border-t"><td className="p-3 font-mono text-xs">TKT-{lead.number}</td><td className="p-3">{lead.name}</td><td className="p-3">{lead.company??'Not set'}</td><td className="p-3"><Badge variant="outline">{lead.status}</Badge></td><td className="p-3">{!lead.converted_client_id&&lead.status!=='won'?<ConvertLeadButton leadId={lead.id} label={lead.email}/>:<span className="text-xs text-muted-foreground">Converted</span>}</td></tr>)}</tbody></table></div>}</section></div>;
}
