import assert from 'node:assert/strict';import test,{beforeEach} from 'node:test';import {registerHooks} from 'node:module';import {createHash} from 'node:crypto';
const id='11111111-1111-4111-8111-111111111111',key=`private/${id}/project_${id}/${id}.pdf`;
const f={};globalThis.__deleteFixture=f;
function reset(){Object.assign(f,{prepared:0,physical:0,ack:0,error:null,completed:false,storageFail:false,ackFail:false,backupFail:false,reads:0,stored:null,existing:null});}reset();beforeEach(reset);
const modules={
 'server-only':'export {};',
 '@/lib/supabase/admin':`export function getSupabaseAdmin(){return {async rpc(name){const f=globalThis.__deleteFixture;if(name==='file_backup_snapshot')return {data:{id:'${id}',r2_key:'${key}',size_bytes:4,filename:'Synthetic.pdf'},error:f.error};if(name!=='prepare_backed_up_file_deletion')throw Error();f.prepared++;return {data:{key:'${key}',completed:f.completed},error:f.error};},from(table){const q={select(){return q;},async maybeSingle(){return {data:globalThis.__deleteFixture.existing,error:null};},update(){globalThis.__deleteFixture.ack++;return q;},eq(){return q;},is(){return q;},then(a,b){return Promise.resolve({error:globalThis.__deleteFixture.ackFail?{message:'synthetic-private'}:null}).then(a,b);}};return q;}};}`,
 '@/lib/r2':`export const CONTACT_MAX_SIZE_BYTES=10485760;export function isPortalKey(key){return key.startsWith('private/');}export async function deletePrivateObjects(){const f=globalThis.__deleteFixture;f.physical++;if(f.storageFail)throw Error('synthetic-private');}`,
 '@/lib/crm/recovery-storage':`export async function readRecoveryBytes(key){const f=globalThis.__deleteFixture;f.reads++;if(f.backupFail)throw Error('synthetic-private');return key.startsWith('private/')?Buffer.from('test'):f.stored;}export async function writeRecoveryBytes(key,bytes){const f=globalThis.__deleteFixture;if(f.backupFail)throw Error('synthetic-private');f.stored=bytes;}`,
};
const hooks=registerHooks({resolve(s,c,n){if(Object.hasOwn(modules,s))return {url:'data:text/javascript,'+encodeURIComponent(modules[s]),shortCircuit:true};if(s==='@/lib/crm/recovery-archive')return {url:new URL('../../lib/crm/recovery-archive.ts',import.meta.url).href,shortCircuit:true};return n(s,c);}});
const {deleteOwnedFile}=await import('../../lib/crm/file-deletion.ts');
const run=()=>deleteOwnedFile(id,{userId:id,role:'admin'});
test('invalid inputs and denied snapshots never read or delete bytes',async()=>{assert.equal((await deleteOwnedFile('invalid',{userId:id,role:'admin'})).ok,false);f.error={message:'denied'};assert.equal((await run()).ok,false);assert.equal(f.reads,0);assert.equal(f.physical,0);});
test('backup failure refuses before database preparation or source deletion',async()=>{f.backupFail=true;assert.equal((await run()).ok,false);assert.equal(f.prepared,0);assert.equal(f.physical,0);});
test('verified backup is retained before physical deletion',async()=>{assert.deepEqual(await run(),{ok:true});assert.ok(f.stored);assert.equal(f.stored.readUInt32LE(0),0x04034b50);assert.equal(f.prepared,1);assert.equal(f.physical,1);assert.equal(f.reads,3);});
test('physical or acknowledgement failure leaves explicit queued recovery',async()=>{f.storageFail=true;assert.match((await run()).error,/queued for retry/);assert.equal(f.ack,0);f.storageFail=false;f.ackFail=true;assert.match((await run()).error,/Tracking is retained/);});
test('completed retry uses saved proof and does not delete bytes again',async()=>{const bytes=Buffer.from('synthetic verified backup');f.existing={file_id:id,requested_by:id,file_snapshot:{id,r2_key:key},recovery_key:`archive/project_${id}/individual_${id}.zip`,sha256:createHash('sha256').update(bytes).digest('hex'),archive_bytes:bytes.length};f.completed=true;assert.deepEqual(await run(),{ok:true});assert.equal(f.physical,0);assert.equal(f.reads,0);});
test.after(()=>hooks.deregister());
