import assert from 'node:assert/strict';
import test from 'node:test';
import {registerHooks} from 'node:module';
import {NextRequest,NextResponse} from 'next/server.js';
import {parseCookieHeader} from '@supabase/ssr';
const id='11111111-1111-4111-8111-111111111111';
const f={options:null,client:null,files:0,result:null,parseCookieHeader};globalThis.__integratedFramework=f;
const modules={
 '@supabase/ssr':'export const parseCookieHeader=globalThis.__integratedFramework.parseCookieHeader;export function createServerClient(u,k,options){const f=globalThis.__integratedFramework;f.options=options;return f.client;}',
 '@/lib/supabase/server':'export async function createSupabaseServerClient(){return globalThis.__integratedFramework.client;}',
 '@/lib/crm/files':'export async function getOwnedFileUrl(){const f=globalThis.__integratedFramework;f.files++;return f.result;}'
};
const hooks=registerHooks({resolve(s,c,n){if(s==='next/server')return n('next/server.js',c);if(s==='@/lib/auth/session')return {url:new URL('../../lib/auth/session.ts',import.meta.url).href,shortCircuit:true};if(Object.hasOwn(modules,s))return {url:'data:text/javascript,'+encodeURIComponent(modules[s]),shortCircuit:true};return n(s,c);}});
const {proxy}=await import('../../proxy.ts');const {getCurrentSession}=await import('../../lib/auth/session.ts');const {GET}=await import('../../app/api/files/[id]/download/route.ts');hooks.deregister();
function setup({role='admin',profile={role,is_active:true},claims={sub:id,email:'synthetic@example.test',app_metadata:{role}},error=null,state='reauthenticate',stateError=null,writes=false}={}){
 f.files=0;f.result={ok:false,error:'synthetic-private'};f.options=null;
 f.client={auth:{async getClaims(){if(writes&&f.options){for(const cookies of [[{name:'session.0',value:'first',options:{path:'/',maxAge:100}},{name:'session.1',value:'second',options:{path:'/',maxAge:100}}],[{name:'session.0',value:'updated',options:{path:'/',maxAge:50}},{name:'session.1',value:'',options:{path:'/',maxAge:0}}]])f.options.cookies.setAll(cookies,{'Cache-Control':'private, no-store',Pragma:'no-cache',Expires:'0',Vary:'Cookie'});}return {data:{claims},error:null};}},from(table){assert.equal(table,'profiles');const q={select(columns){assert.equal(columns.replaceAll(' ',''),'role,is_active');return q;},eq(column,value){assert.equal(column,'id');assert.equal(value,id);return q;},async maybeSingle(){return {data:profile,error};}};return q;},async rpc(name){assert.equal(name,'caller_account_state');return {data:state,error:stateError};}};
}
const request=path=>new NextRequest('https://example.test'+path,{headers:{cookie:'unrelated=keep'}});
const download=()=>GET(request('/api/files/'+id+'/download'),{params:Promise.resolve({id})});
test('integrated real Next session cookie authority and opaque download contracts',async t=>{
 const names=['NODE_ENV','NEXT_PUBLIC_SUPABASE_URL','NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY'];const before=Object.fromEntries(names.map(n=>[n,process.env[n]]));const fetchBefore=globalThis.fetch;
 process.env.NODE_ENV='production';process.env.NEXT_PUBLIC_SUPABASE_URL='https://example.test';process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY='synthetic';globalThis.fetch=async()=>{throw new Error('Network forbidden');};
 try{
  await t.test('active roles require live matching authority',async()=>{for(const role of ['admin','client']){setup({role});assert.deepEqual(await getCurrentSession(),{userId:id,email:'synthetic@example.test',role});setup({role,profile:{role,is_active:false}});assert.equal(await getCurrentSession(),null);}setup({profile:{role:'client',is_active:true}});assert.equal(await getCurrentSession(),null);});
  await t.test('chunked refresh uses real downstream and browser cookie serialization',async()=>{setup({writes:true});const req=request('/admin');const r=await proxy(req);assert.ok(r instanceof NextResponse);assert.equal(r.status,200);assert.equal(req.cookies.get('session.0').value,'updated');assert.equal(new NextRequest('https://example.test',{headers:{cookie:r.headers.get('x-middleware-request-cookie')}}).cookies.get('unrelated').value,'keep');assert.equal(r.cookies.get('session.0').value,'updated');assert.equal(r.cookies.get('session.1').value,'');const lines=r.headers.getSetCookie();assert.equal(lines.length,2);for(const line of lines){assert.match(line,/HttpOnly/i);assert.match(line,/Secure/i);assert.match(line,/SameSite=lax/i);}assert.match(lines.find(x=>x.startsWith('session.1=')),/Max-Age=0/);});
  await t.test('wrong-role redirects preserve cookie/cache fields without continuation headers',async()=>{setup({role:'client',writes:true});const r=await proxy(request('/admin'));assert.equal(r.status,307);assert.equal(r.headers.get('location'),'https://example.test/portal');assert.equal(r.headers.getSetCookie().length,2);assert.equal(r.headers.get('cache-control'),'private, no-store');assert.equal(r.headers.get('x-middleware-next'),null);assert.equal(r.headers.get('x-middleware-request-cookie'),null);});
  await t.test('RLS-hidden inactive profile uses caller-only state rather than stale claims',async()=>{setup({profile:null,state:'inactive'});const r=await proxy(request('/admin'));assert.equal(r.headers.get('location'),'https://example.test/api/auth/logout?reason=deactivated');assert.equal((await proxy(request('/login'))).headers.get('location'),null);setup({profile:null,stateError:{message:'synthetic-private'}});const denied=await proxy(request('/admin'));assert.equal(denied.status,503);assert.equal(denied.headers.get('cache-control'),'no-store');assert.equal(await denied.text(),'Authentication is temporarily unavailable.');});
  await t.test('anonymous file requests are 401; rejected verified identities are opaque 404',async()=>{setup({claims:null});let r=await download();assert.equal(r.status,401);assert.deepEqual(await r.json(),{error:'Unauthorized'});assert.equal(f.files,0);for(const profile of [null,{role:'admin',is_active:false},{role:'client',is_active:true}]){setup({profile});r=await download();assert.equal(r.status,404);assert.deepEqual(await r.json(),{error:'File not found.'});assert.equal(r.headers.get('cache-control'),'no-store');assert.equal(f.files,0);}});
  await t.test('accepted session cannot expose provider errors and signed redirect is not fetched',async()=>{setup();let r=await download();assert.equal(r.status,404);assert.deepEqual(await r.json(),{error:'File not found.'});setup();f.result={ok:true,url:'https://example.test/synthetic-download',filename:'Synthetic.pdf'};r=await download();assert.equal(r.status,302);assert.equal(r.headers.get('location'),f.result.url);assert.equal(r.headers.get('cache-control'),'private, no-store');});
  await t.test('credential pages stay reachable and missing config preserves intended destination',async()=>{setup({profile:null});for(const path of ['/reset-password','/invite/accept'])assert.equal((await proxy(request(path))).status,200);delete process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;const r=await proxy(request('/portal/files?page=2'));assert.equal(new URL(r.headers.get('location')).searchParams.get('next'),'/portal/files?page=2');assert.equal((await proxy(request('/login'))).status,200);});
 }finally{globalThis.fetch=fetchBefore;for(const name of names){if(before[name]===undefined)delete process.env[name];else process.env[name]=before[name];}delete globalThis.__integratedFramework;}
});
