import assert from 'node:assert/strict';
import {registerHooks} from 'node:module';
import test from 'node:test';
const f={events:[],outcomes:[],saved:[],recipient:'synthetic@example.test',recipientError:null,envelopeFail:false,checks:0};globalThis.__outboxTest=f;
const modules={'server-only':'export {};','@/lib/supabase/admin':`export function getSupabaseAdmin(){const f=globalThis.__outboxTest;return {rpc:async(name,args)=>{if(name==='claim_email_event')return {data:f.events.splice(0,1),error:null};if(name==='email_dispatch_recipient'){f.checks++;return {data:typeof f.recipient==='function'?f.recipient(f.checks):f.recipient,error:f.recipientError};}f.outcomes.push(args);return {data:true,error:null};},from(){const q={select(){return q;},eq(){return q;},update(value){f.saved.push(value);return q;},async maybeSingle(){return {data:f.envelopeFail?null:{id:'synthetic'},error:null};}};return q;}};}`};
const hooks=registerHooks({resolve(s,c,n){if(Object.hasOwn(modules,s))return {url:'data:text/javascript,'+encodeURIComponent(modules[s]),shortCircuit:true};if(s==='@/lib/email/templates')return {url:new URL('../../lib/email/templates.ts',import.meta.url).href,shortCircuit:true};return n(s,c);}});
const {drainEmailOutbox}=await import('../../lib/email/outbox.ts');const {sendEmail}=await import('../../lib/email/index.ts');hooks.deregister();
const original=globalThis.fetch;test.after(()=>globalThis.fetch=original);
function setup(){f.events=[{id:'11111111-1111-4111-8111-111111111111',lease_token:'synthetic-lease',template:'new-ticket',entity_id:'22222222-2222-4222-8222-222222222222',recipient_id:'synthetic-user',payload:{ticketNumber:1000,subject:'Synthetic'},envelope:null}];f.outcomes=[];f.saved=[];f.recipient='synthetic@example.test';f.recipientError=null;f.envelopeFail=false;f.checks=0;process.env.NEXT_PUBLIC_SITE_URL='https://example.test';process.env.RESEND_API_KEY='synthetic';process.env.RESEND_FROM_EMAIL='synthetic@example.test';}
test('durable envelope and current authority precede fixed-origin transport',async()=>{setup();globalThis.fetch=async(url,options)=>{assert.equal(f.saved.length,1);assert.equal(f.checks,2);assert.equal(url,'https://api.resend.com/emails');assert.equal(options.redirect,'error');assert.equal(options.headers['Idempotency-Key'],'lifecycle/11111111-1111-4111-8111-111111111111');return new Response(JSON.stringify({id:'synthetic-provider'}));};assert.deepEqual(await drainEmailOutbox(1),{accepted:1,deferred:0,failed:0});});
test('provider timeout remains retryable without raw diagnostics',async()=>{setup();globalThis.fetch=async()=>{throw Object.assign(new Error('synthetic-private-payload'),{name:'TimeoutError'});};assert.equal((await drainEmailOutbox(1)).deferred,1);assert.equal(f.outcomes[0].p_error,'provider_timeout');assert.equal(JSON.stringify(f.outcomes).includes('synthetic-private'),false);});
test('revoked recipients and superseded frozen addresses never send',async()=>{for(const variation of ['revoked','changed','revoked-after-render']){setup();if(variation==='revoked')f.recipient=null;if(variation==='changed')f.events[0].envelope={to:'old@example.test',from:'synthetic@example.test',subject:'Synthetic',html:'Synthetic'};if(variation==='revoked-after-render')f.recipient=checks=>checks===1?'synthetic@example.test':null;let sends=0;globalThis.fetch=async()=>{sends++;return new Response('{}');};assert.equal((await drainEmailOutbox(1)).failed,1);assert.equal(f.outcomes[0].p_state,'suppressed');assert.equal(sends,0);}});
test('recipient-check outage and failed envelope persistence defer without transport',async()=>{for(const mode of ['check','save']){setup();if(mode==='check')f.recipientError={message:'synthetic-private-db'};else f.envelopeFail=true;let sends=0;globalThis.fetch=async()=>{sends++;return new Response('{}');};assert.equal((await drainEmailOutbox(1)).deferred,1);assert.equal(sends,0);assert.equal(JSON.stringify(f.outcomes).includes('synthetic-private'),false);}});
test('409 concurrency retries, payload conflict and unknown categories stop',async()=>{for(const [status,body,retry]of[[409,{name:'concurrent_idempotent_requests',message:'synthetic-private'},true],[409,{name:'invalid_idempotent_request'},false],[409,{name:'unknown'},false],[409,'invalid-json',false],[429,{},true],[500,{},true],[400,{},false]]){setup();globalThis.fetch=async()=>new Response(typeof body==='string'?body:JSON.stringify(body),{status});const result=await drainEmailOutbox(1);assert.equal(result.deferred,retry?1:0);assert.equal(f.outcomes[0].p_state,retry?'pending':'failed');assert.equal(JSON.stringify(f.outcomes).includes('synthetic-private'),false);}});
test('oversized 409 response fails closed',async()=>{setup();globalThis.fetch=async()=>new Response(JSON.stringify({name:'concurrent_idempotent_requests',message:'x'.repeat(5000)}),{status:409});assert.equal((await drainEmailOutbox(1)).failed,1);});
test('legacy helper cannot double-send',async()=>{globalThis.fetch=async()=>{assert.fail('legacy transport disabled');};assert.equal((await sendEmail({to:'synthetic@example.test',template:'new-ticket',rendered:{subject:'Synthetic',html:'Synthetic'}})).ok,false);});
