import assert from 'node:assert/strict';
import {registerHooks} from 'node:module';
import test from 'node:test';
const f={events:[],outcomes:[],saved:[],active:true,envelopeFail:false};globalThis.__outboxTest=f;
const modules={'server-only':'export {};','@/lib/supabase/admin':`export function getSupabaseAdmin(){const f=globalThis.__outboxTest;return {rpc:async(name,args)=>{if(name==='claim_email_event')return {data:f.events.splice(0,1),error:null};f.outcomes.push(args);return {data:true,error:null};},auth:{admin:{getUserById:async()=>({data:{user:{email:'synthetic@example.test'}},error:null})}},from(table){const q={select(){return q;},eq(){return q;},update(value){f.saved.push(value);return q;},async maybeSingle(){return table==='profiles'?{data:{is_active:f.active},error:null}:{data:f.envelopeFail?null:{id:'synthetic'},error:null};}};return q;}};}`};
const hooks=registerHooks({resolve(s,c,n){if(Object.hasOwn(modules,s))return {url:`data:text/javascript,${encodeURIComponent(modules[s])}`,shortCircuit:true};if(s==='@/lib/email/templates')return {url:new URL('../../lib/email/templates.ts',import.meta.url).href,shortCircuit:true};return n(s,c);}});
const {drainEmailOutbox}=await import('../../lib/email/outbox.ts');
const {sendEmail}=await import('../../lib/email/index.ts');hooks.deregister();
const original=globalThis.fetch;test.after(()=>globalThis.fetch=original);
function setup(){f.events=[{id:'11111111-1111-4111-8111-111111111111',lease_token:'synthetic-lease',template:'new-ticket',entity_id:'22222222-2222-4222-8222-222222222222',recipient_id:'synthetic-user',payload:{ticketNumber:1000,subject:'Synthetic'},envelope:null}];f.outcomes=[];f.saved=[];f.active=true;f.envelopeFail=false;process.env.NEXT_PUBLIC_SITE_URL='https://example.test';process.env.RESEND_API_KEY='synthetic';process.env.RESEND_FROM_EMAIL='synthetic@example.test';}
test('durable envelope exists before transport and uses stable event identity',async()=>{setup();globalThis.fetch=async(url,options)=>{assert.equal(f.saved.length,1);assert.equal(url,'https://api.resend.com/emails');assert.equal(options.headers['Idempotency-Key'],'lifecycle/11111111-1111-4111-8111-111111111111');return new Response(JSON.stringify({id:'synthetic-provider'}));};assert.deepEqual(await drainEmailOutbox(1),{accepted:1,deferred:0,failed:0});assert.equal(f.outcomes[0].p_state,'accepted');});
test('provider timeout keeps a retryable event with fixed diagnostics',async()=>{setup();globalThis.fetch=async()=>{throw Object.assign(new Error('synthetic-private-provider-payload'),{name:'TimeoutError'});};assert.equal((await drainEmailOutbox(1)).deferred,1);assert.equal(f.outcomes[0].p_error,'provider_timeout');assert.equal(JSON.stringify(f.outcomes).includes('synthetic-private'),false);});
test('failed envelope persistence and inactive recipients never send',async()=>{setup();f.envelopeFail=true;globalThis.fetch=async()=>{assert.fail('must not send');};assert.equal((await drainEmailOutbox(1)).deferred,1);assert.equal(f.outcomes[0].p_error,'audit_unavailable');setup();f.active=false;assert.equal((await drainEmailOutbox(1)).failed,1);assert.equal(f.outcomes[0].p_state,'suppressed');});
test('legacy send helper cannot double-send an already captured event',async()=>{globalThis.fetch=async()=>{assert.fail('legacy transport disabled');};const result=await sendEmail({to:'synthetic@example.test',template:'new-ticket',rendered:{subject:'Synthetic',html:'Synthetic'}});assert.equal(result.ok,false);assert.match(result.error,/durable outbox/);});
