import assert from 'node:assert/strict';import test from 'node:test';import {registerHooks} from 'node:module';
const id='11111111-1111-4111-8111-111111111111',owner='22222222-2222-4222-8222-222222222222';
const f={rows:[],reads:0,limit:null,foreign:false,error:false};globalThis.__threadFixture=f;
const admin={from(table){let limit=null,filter=null;const order=[],eq=[];const q={select(){return q;},eq(k,v){eq.push([k,v]);return q;},or(v){filter=v;return q;},order(k,o){order.push([k,o]);return q;},limit(n){limit=n;f.limit=n;return q;},async maybeSingle(){assert.ok(eq.some(([k,v])=>k==='id'&&v===id));return {data:f.foreign?null:{id,client_id:owner,number:1,subject:'Synthetic',status:'open',profiles:null},error:null};},then(resolve,reject){f.reads++;assert.ok(eq.some(([k,v])=>k==='ticket_id'&&v===id));let rows=[...f.rows];if(filter){const m=filter.match(/^created_at\.(lt|gt)\.(.+),and\(created_at.eq\.(.+),id\.(lt|gt)\.([0-9a-f-]+)\)$/);assert.ok(m);assert.equal(m[1],m[4]);assert.equal(m[2],m[3]);rows=rows.filter(r=>m[1]==='lt'?(r.created_at<m[2]||(r.created_at===m[2]&&r.id<m[5])):(r.created_at>m[2]||(r.created_at===m[2]&&r.id>m[5])));}
 rows.sort((a,b)=>a.created_at.localeCompare(b.created_at)||a.id.localeCompare(b.id));if(order[0]?.[1]?.ascending===false)rows.reverse();return Promise.resolve({data:limit===null?rows:rows.slice(0,limit),error:f.error?{}:null}).then(resolve,reject);}};return q;},auth:{admin:{async getUserById(){return {data:{user:{email:'fixture@example.test'}}};}}}};globalThis.__threadAdmin=admin;
const modules={'server-only':'export {};','@/lib/supabase/admin':'export function getSupabaseAdmin(){return globalThis.__threadAdmin;}','@/lib/email':'export function queueEmail(){}'+['recordUnsent','sendNewTicketEmail','sendReplyPostedEmail','sendStatusChangedEmail','sendToAll'].map(n=>`export async function ${n}(){throw Error("Unexpected email");}`).join(''),'@/lib/email/recipients':['adminRecipients','emailOrigin','recipientEmail','recipientName','ticketEmailContext'].map(n=>`export async function ${n}(){throw Error("Unexpected email");}`).join('')};
registerHooks({resolve(s,c,n){if(Object.hasOwn(modules,s))return {url:'data:text/javascript,'+encodeURIComponent(modules[s]),shortCircuit:true};if(s.startsWith('@/lib/'))return {url:new URL('../../'+s.slice(2)+'.ts',import.meta.url).href,shortCircuit:true};return n(s,c);}});
const {getOwnTicketThread,getTicketThread}=await import('../../lib/crm/tickets.ts');
const {decodeThreadCursor,encodeThreadCursor}=await import('../../lib/crm/thread-pagination.ts');
function reset(n=51){Object.assign(f,{reads:0,limit:null,foreign:false,error:false,rows:Array.from({length:n},(_,i)=>({id:'33333333-3333-4333-8333-'+String(i).padStart(12,'0'),created_at:'2026-09-12T00:00:00.123456+00:00',body:'Synthetic '+i,profiles:null}))});}
test('thread latest page is bounded and chronological for client and admin',async()=>{for(const read of [()=>getOwnTicketThread(owner,id),()=>getTicketThread(id)]){reset();const r=await read();assert.equal(r.ok,true);assert.equal(r.messages.length,50);assert.equal(f.limit,51);assert.equal(r.messages[0].id,f.rows[1].id);assert.equal(r.messages[49].id,f.rows[50].id);assert.ok(r.pageInfo.olderCursor);assert.equal(r.pageInfo.isLatest,true);}});
test('empty thread remains a valid page',async()=>{reset(0);const r=await getOwnTicketThread(owner,id);assert.equal(r.ok,true);assert.deepEqual(r.messages,[]);assert.equal(r.pageInfo.olderCursor,null);});
test('message service error is retryable rather than not found',async()=>{reset();f.error=true;const r=await getOwnTicketThread(owner,id);assert.equal(r.ok,false);assert.equal(r.kind,'unavailable');assert.equal(r.error,'Could not load messages.');});
test('foreign ticket denial does not hydrate messages',async()=>{reset();f.foreign=true;const r=await getOwnTicketThread(owner,id);assert.equal(r.ok,false);assert.equal(r.kind,'not_found');assert.equal(f.reads,0);});
test('malformed cursor is rejected without message reads',async()=>{reset();const r=await getOwnTicketThread(owner,id,'not-valid');assert.equal(r.ok,false);assert.equal(r.kind,'invalid_cursor');assert.equal(f.reads,0);});
test('fixed data traverses both directions without omissions or duplicates',async()=>{for(const n of [1,49,50,51,1007,10000]){reset(n);const seen=[];let page=await getOwnTicketThread(owner,id);while(true){assert.ok(page.ok);assert.ok(page.messages.length<=50);seen.push(...page.messages.map(r=>r.id));if(!page.pageInfo.olderCursor)break;page=await getOwnTicketThread(owner,id,page.pageInfo.olderCursor);}assert.equal(new Set(seen).size,n);assert.equal(seen.length,n);const forward=[...page.messages.map(r=>r.id)];while(page.pageInfo.newerCursor){page=await getOwnTicketThread(owner,id,page.pageInfo.newerCursor);assert.ok(page.ok);forward.push(...page.messages.map(r=>r.id));}assert.deepEqual(forward,f.rows.map(r=>r.id));}});
test('cursor preserves microseconds and rejects malformed/cross-ticket input',()=>{reset();const cursor=encodeThreadCursor(id,f.rows[0],'older');assert.equal(decodeThreadCursor(cursor,id).createdAt,'2026-09-12T00:00:00.123456+00:00');assert.equal(decodeThreadCursor(cursor,owner),false);assert.equal(decodeThreadCursor([cursor],id),false);for(const patch of [{createdAt:'2026-02-30T00:00:00Z'},{id:'x),ticket_id.neq.y'},{v:2},{extra:true}]){const raw=Buffer.from(JSON.stringify({...JSON.parse(Buffer.from(cursor,'base64url').toString()),...patch})).toString('base64url');assert.equal(decodeThreadCursor(raw,id),false);}});
test('newer insert does not move the older keyset boundary',async()=>{reset(101);const first=await getOwnTicketThread(owner,id);const boundary=first.pageInfo.olderCursor;f.rows.push({...f.rows[100],id:'44444444-4444-4444-8444-444444444444',created_at:'2026-09-12T00:00:01.000001+00:00'});const older=await getOwnTicketThread(owner,id,boundary);assert.equal(older.messages[49].id,f.rows[50].id);assert.equal((await getOwnTicketThread(owner,id)).messages.at(-1).id,f.rows.at(-1).id);});
