import assert from 'node:assert/strict';import test from 'node:test';import {registerHooks} from 'node:module';
const id='11111111-1111-4111-8111-111111111111',owner='22222222-2222-4222-8222-222222222222';
const f={rows:[],reads:0,limit:null,foreign:false,error:false};globalThis.__threadFixture=f;
const admin={from(table){let limit=null;const order=[];const q={select(){return q;},eq(){return q;},order(k,o){order.push([k,o]);return q;},limit(n){limit=n;f.limit=n;return q;},async maybeSingle(){return {data:f.foreign?null:{id,client_id:owner,number:1,subject:'Synthetic',status:'open',profiles:null},error:null};},then(resolve,reject){f.reads++;const rows=[...f.rows];if(order[0]?.[1]?.ascending===false)rows.reverse();return Promise.resolve({data:limit===null?rows:rows.slice(0,limit),error:f.error?{}:null}).then(resolve,reject);}};return q;},auth:{admin:{async getUserById(){return {data:{user:{email:'fixture@example.test'}}};}}}};globalThis.__threadAdmin=admin;
const modules={'server-only':'export {};','@/lib/supabase/admin':'export function getSupabaseAdmin(){return globalThis.__threadAdmin;}','@/lib/email':'export function queueEmail(){}'+['recordUnsent','sendNewTicketEmail','sendReplyPostedEmail','sendStatusChangedEmail','sendToAll'].map(n=>`export async function ${n}(){throw Error("Unexpected email");}`).join(''),'@/lib/email/recipients':['adminRecipients','emailOrigin','recipientEmail','recipientName','ticketEmailContext'].map(n=>`export async function ${n}(){throw Error("Unexpected email");}`).join('')};
registerHooks({resolve(s,c,n){if(Object.hasOwn(modules,s))return {url:'data:text/javascript,'+encodeURIComponent(modules[s]),shortCircuit:true};if(s.startsWith('@/lib/'))return {url:new URL('../../'+s.slice(2)+'.ts',import.meta.url).href,shortCircuit:true};return n(s,c);}});
const {getOwnTicketThread,getTicketThread}=await import('../../lib/crm/tickets.ts');
function reset(n=51){Object.assign(f,{reads:0,limit:null,foreign:false,error:false,rows:Array.from({length:n},(_,i)=>({id:'33333333-3333-4333-8333-'+String(i).padStart(12,'0'),created_at:'2026-09-12T00:00:00.123456+00:00',body:'Synthetic '+i,profiles:null}))});}
test('thread latest page is bounded and chronological for client and admin',async()=>{for(const read of [()=>getOwnTicketThread(owner,id),()=>getTicketThread(id)]){reset();const r=await read();assert.equal(r.ok,true);assert.equal(r.messages.length,50);assert.equal(f.limit,51);assert.equal(r.messages[0].id,f.rows[1].id);assert.equal(r.messages[49].id,f.rows[50].id);assert.ok(r.pageInfo.olderCursor);assert.equal(r.pageInfo.isLatest,true);}});
test('empty thread remains a valid page',async()=>{reset(0);const r=await getOwnTicketThread(owner,id);assert.equal(r.ok,true);assert.deepEqual(r.messages,[]);assert.equal(r.pageInfo.olderCursor,null);});
test('message service error is retryable rather than not found',async()=>{reset();f.error=true;const r=await getOwnTicketThread(owner,id);assert.equal(r.ok,false);assert.equal(r.kind,'unavailable');assert.equal(r.error,'Could not load messages.');});
test('foreign ticket denial does not hydrate messages',async()=>{reset();f.foreign=true;const r=await getOwnTicketThread(owner,id);assert.equal(r.ok,false);assert.equal(r.kind,'not_found');assert.equal(f.reads,0);});
test('malformed cursor is rejected without message reads',async()=>{reset();const r=await getOwnTicketThread(owner,id,'not-valid');assert.equal(r.ok,false);assert.equal(r.kind,'invalid_cursor');assert.equal(f.reads,0);});
