import assert from 'node:assert/strict';
import {registerHooks} from 'node:module';
import test,{beforeEach} from 'node:test';
// Actual attachment/action modules, synthetic external boundaries. Immutable
// service integrity is independently tested in immutable-upload.test.mjs.
const clientId='11111111-1111-4111-8111-111111111111',otherClientId='22222222-2222-4222-8222-222222222222',adminId='33333333-3333-4333-8333-333333333333',ticketId='44444444-4444-4444-8444-444444444444',otherTicketId='55555555-5555-4555-8555-555555555555',fileUuid1='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',fileUuid2='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
const fixture={};globalThis.__ticketAttachmentFixture=fixture;
function reset(){process.env.LEAD_IP_HASH_SALT='synthetic-salt';Object.assign(fixture,{session:{userId:clientId,role:'client'},profile:{id:clientId,role:'client',is_active:true},ticket:{id:ticketId,client_id:clientId},existingAttachmentCount:0,r2Configured:true,rateLimitAllowed:true,rateLimitError:null,storedObjects:new Map(),atomicAttachError:null,atomicAttachCalls:[],createTicketCalls:[],revalidated:[],redirected:null,finalized:0});}reset();beforeEach(reset);
const unexpected='throw new Error("Unexpected dependency call in ticket-attachments test");',r2Url=new URL('../../lib/r2.ts',import.meta.url).href;
const modules={
 'server-only':'export {};',
 'next/server':'export class NextRequest extends Request {} export class NextResponse {static json(body,init={}){return new Response(JSON.stringify(body),{...init,headers:{"Content-Type":"application/json",...init?.headers}});}}',
 'next/cache':'export function revalidatePath(path){globalThis.__ticketAttachmentFixture.revalidated.push(path);}',
 'next/navigation':'export function redirect(url){globalThis.__ticketAttachmentFixture.redirected=url;const err=new Error("NEXT_REDIRECT");err.digest="NEXT_REDIRECT";throw err;}',
 '@/lib/auth/session':'export async function getCurrentSession(){return globalThis.__ticketAttachmentFixture.session;}',
 '@/lib/email':'export function queueEmail(){}\n'+['recordUnsent','sendNewTicketEmail','sendReplyPostedEmail','sendStatusChangedEmail','sendDeliverableUploadedEmail','sendInvoiceIssuedEmail','sendPaymentConfirmedEmail','sendToAll'].map(n=>`export async function ${n}(){${unexpected}}`).join('\n'),
 '@/lib/email/recipients':'export function formatMoney(a,c){return String(a);}\n'+['adminRecipients','emailOrigin','recipientEmail','recipientName','ticketEmailContext'].map(n=>`export async function ${n}(){${unexpected}}`).join('\n'),
 '@/lib/crm/immutable-upload':'export function isImmutableUploadKey(){return false;}export async function verifyImmutableUpload(){throw Error("Unexpected final key");}export async function finalizeUpload(key,size){const f=globalThis.__ticketAttachmentFixture;if(f.storedObjects.get(key)!==size)throw Error("Missing source");f.finalized++;return {key:key.replace(/-4([a-f0-9]{3})-/g,"-5$1-")};}',
 '@/lib/r2':`import {validateContactFile,makePendingAttachmentKey,makeTicketAttachmentKey} from '${r2Url}';export {validateContactFile,makePendingAttachmentKey,makeTicketAttachmentKey};export function isR2Configured(){return globalThis.__ticketAttachmentFixture.r2Configured!==false;}export async function presignPrivatePut(key){return 'https://synthetic-r2.test/'+key+'?signed=true';}export async function verifyStoredObjectSize(key,declared){if(!Number.isSafeInteger(declared)||declared<1||declared>10485760)return false;return globalThis.__ticketAttachmentFixture.storedObjects.get(key)===declared;}`,
 '@/lib/supabase/admin':`export function getSupabaseAdmin(){return {from(table){const f=globalThis.__ticketAttachmentFixture,filters=[];let countMode=null,isHead=false;const q={select(cols,opts){if(opts?.count)countMode=opts.count;if(opts?.head)isHead=true;return q;},eq(key,value){filters.push([key,value]);return q;},async maybeSingle(){const id=filters.find(([k])=>k==='id')?.[1];if(table==='profiles')return {data:f.profile&&f.profile.id===id?{...f.profile}:null,error:null};if(table==='tickets')return {data:f.ticket&&f.ticket.id===id?{...f.ticket}:null,error:null};throw Error('Unexpected table');},then(a,b){if(table==='files'&&countMode==='exact'&&isHead)return Promise.resolve({count:f.existingAttachmentCount,error:null}).then(a,b);return Promise.resolve({data:[],error:null}).then(a,b);}};return q;},async rpc(name,args){const f=globalThis.__ticketAttachmentFixture;if(name==='consume_rate_limit')return f.rateLimitError?{data:null,error:f.rateLimitError}:{data:f.rateLimitAllowed,error:null};if(name==='attach_ticket_files_atomic'){f.atomicAttachCalls.push(args);return {data:null,error:f.atomicAttachError};}if(name==='create_ticket_atomic'){f.createTicketCalls.push(args);return {data:'${ticketId}',error:null};}throw Error('Unexpected RPC');}};}`,
};
registerHooks({resolve(s,c,n){if(Object.hasOwn(modules,s))return {url:'data:text/javascript,'+encodeURIComponent(modules[s]),shortCircuit:true};if(s.startsWith('@/lib/'))return {url:new URL('../../'+s.slice(2)+'.ts',import.meta.url).href,shortCircuit:true};return n(s,c);}});
const {prepareTicketUploads,validateAttachments,ATTACHMENT_ERROR}=await import('../../lib/crm/attachments.ts');const {shareTicketFilesAction}=await import('../../lib/crm/ticket-upload-actions.ts');const {createTicketWithAttachmentsAction,confirmTicketAttachmentAction}=await import('../../lib/crm/client-actions.ts');const {NextRequest}=await import('next/server');const {POST:ticketPresignPost}=await import('../../app/api/uploads/ticket-presign/route.ts');
const file={filename:'doc.pdf',mime:'application/pdf',size:100};const actor={userId:clientId,role:'client'};
test('prepare: rejects invalid actor userId or malformed ticketId UUID',async()=>{for(const [a,t]of [[{userId:'not-a-uuid',role:'client'},null],[actor,'malformed-ticket-id']]){const r=await prepareTicketUploads(a,t,[file]);assert.equal(r.ok,false);assert.equal(r.status,400);}});
test('prepare: rejects if actor profile is missing, inactive, or role mismatches',async()=>{for(const profile of [null,{id:clientId,role:'client',is_active:false},{id:clientId,role:'admin',is_active:true}]){fixture.profile=profile;const r=await prepareTicketUploads(actor,null,[file]);assert.equal(r.ok,false);assert.equal(r.status,401);}});
test('prepare: admin cannot request uploads without a ticketId',async()=>{fixture.profile={id:adminId,role:'admin',is_active:true};const r=await prepareTicketUploads({userId:adminId,role:'admin'},null,[file]);assert.equal(r.ok,false);assert.equal(r.status,400);assert.equal(r.error,'Choose a ticket first.');});
test('prepare: client can request pending uploads without a ticketId',async()=>{const r=await prepareTicketUploads(actor,null,[{...file,size:1024}]);assert.equal(r.ok,true);assert.equal(r.uploads.length,1);assert.ok(r.uploads[0].key.startsWith(`private/${clientId}/pending/`));assert.ok(r.uploads[0].key.endsWith('.pdf'));assert.ok(r.uploads[0].uploadUrl.includes(r.uploads[0].key));});
test('prepare: client requesting foreign ticketId returns 404',async()=>{fixture.ticket={id:ticketId,client_id:otherClientId};const r=await prepareTicketUploads(actor,ticketId,[file]);assert.equal(r.ok,false);assert.equal(r.status,404);assert.equal(r.error,'Ticket not found.');});
test('prepare: admin requesting any valid ticket succeeds with ticket-scoped keys',async()=>{fixture.profile={id:adminId,role:'admin',is_active:true};const r=await prepareTicketUploads({userId:adminId,role:'admin'},ticketId,[{filename:'receipt.png',mime:'image/png',size:2048}]);assert.equal(r.ok,true);assert.equal(r.uploads.length,1);assert.ok(r.uploads[0].key.startsWith(`private/${clientId}/ticket_${ticketId}/`));assert.ok(r.uploads[0].key.endsWith('.png'));});
test('prepare: existing ticket with attachments exceeding 10 cap returns 400',async()=>{fixture.existingAttachmentCount=9;const r=await prepareTicketUploads(actor,ticketId,[file,file]);assert.equal(r.ok,false);assert.equal(r.status,400);assert.equal(r.error,'A ticket can have at most 10 attachments.');});
test('prepare: files count out of bounds returns 400',async()=>{for(const files of [[],Array.from({length:11},()=>file)]){const r=await prepareTicketUploads(actor,null,files);assert.equal(r.ok,false);assert.equal(r.status,400);}});
test('prepare: invalid file metadata fails before storage or rate limit consumption',async()=>{for(const bad of [{filename:'bad.exe',mime:'application/x-msdownload',size:100},{filename:'fake.pdf',mime:'image/png',size:100},{...file,size:10485761},{...file,size:0},{...file,size:10.5}]){const r=await prepareTicketUploads(actor,null,[bad]);assert.equal(r.ok,false);assert.equal(r.status,400);}});
test('prepare: rate limit exhaustion returns 429',async()=>{fixture.rateLimitAllowed=false;const r=await prepareTicketUploads(actor,null,[file]);assert.equal(r.ok,false);assert.equal(r.status,429);assert.equal(r.error,'Too many upload requests. Please try again later.');});
test('prepare: rate limit error or missing salt returns 503 fail-closed',async()=>{fixture.rateLimitError={message:'db error'};assert.equal((await prepareTicketUploads(actor,null,[file])).status,503);delete process.env.LEAD_IP_HASH_SALT;assert.equal((await prepareTicketUploads(actor,null,[file])).status,503);});
function entry(key,size=500){return {key,filename:'doc.pdf',mime:'application/pdf',size_bytes:size};}const tk=()=>`private/${clientId}/ticket_${ticketId}/${fileUuid1}.pdf`;
test('validate: invalid owner UUID or ticketId UUID returns null',async()=>{assert.equal(await validateAttachments([],'invalid-uuid',ticketId),null);assert.equal(await validateAttachments([],clientId,'invalid-ticket-uuid'),null);});
test('validate: entries not an array or exceeding 10 returns null',async()=>{for(const v of [null,'string',Array.from({length:11},()=>({}))])assert.equal(await validateAttachments(v,clientId,ticketId),null);});
test('validate: empty entries returns an empty array',async()=>{assert.deepEqual(await validateAttachments([],clientId,ticketId),[]);assert.equal(fixture.finalized,0);});
test('validate: pending key submitted against existing ticket returns null',async()=>{const k=`private/${clientId}/pending/${fileUuid1}.pdf`;fixture.storedObjects.set(k,500);assert.equal(await validateAttachments([entry(k)],clientId,ticketId),null);});
test('validate: ticket key submitted against pending returns null',async()=>{fixture.storedObjects.set(tk(),500);assert.equal(await validateAttachments([entry(tk())],clientId,null),null);});
test('validate: cross-ticket key or foreign ownerId returns null',async()=>{for(const k of [tk().replace(ticketId,otherTicketId),tk().replace(clientId,otherClientId)]){fixture.storedObjects.set(k,500);assert.equal(await validateAttachments([entry(k)],clientId,ticketId),null);}});
test('validate: directory traversal attempt in key returns null',async()=>{assert.equal(await validateAttachments([entry(`private/${clientId}/ticket_${ticketId}/../../etc/passwd.pdf`)],clientId,ticketId),null);});
test('validate: duplicate keys in same batch returns null',async()=>{fixture.storedObjects.set(tk(),500);assert.equal(await validateAttachments([entry(tk()),entry(tk())],clientId,ticketId),null);});
test('validate: missing object in R2 returns null',async()=>{assert.equal(await validateAttachments([entry(tk())],clientId,ticketId),null);});
test('validate: stored object byte count mismatch returns null',async()=>{fixture.storedObjects.set(tk(),501);assert.equal(await validateAttachments([entry(tk())],clientId,ticketId),null);});
test('validate: single corrupt or missing file in batch fails all-or-nothing',async()=>{const k2=`private/${clientId}/ticket_${ticketId}/${fileUuid2}.png`;fixture.storedObjects.set(tk(),500);fixture.storedObjects.set(k2,999);assert.equal(await validateAttachments([entry(tk()),{key:k2,filename:'pic.png',mime:'image/png',size_bytes:800}],clientId,ticketId),null);assert.equal(fixture.finalized,0);});
test('validate: valid entries succeed and normalize mime before finalization',async()=>{const k2=`private/${clientId}/ticket_${ticketId}/${fileUuid2}.png`;fixture.storedObjects.set(tk(),500);fixture.storedObjects.set(k2,800);const r=await validateAttachments([{...entry(tk()),mime:'APPLICATION/PDF; charset=utf-8'},{key:k2,filename:'pic.png',mime:'image/png',size_bytes:800}],clientId,ticketId);assert.ok(Array.isArray(r));assert.equal(r.length,2);assert.equal(r[0].mime,'application/pdf');assert.equal(r[1].mime,'image/png');assert.equal(fixture.finalized,2);assert.notEqual(r[0].key,tk());});
test('share: anonymous caller returns Unauthorized without writes',async()=>{fixture.session=null;assert.equal((await shareTicketFilesAction(ticketId,[])).error,'Unauthorized.');assert.equal(fixture.atomicAttachCalls.length+fixture.finalized,0);});
test('share: inactive profile or role mismatch returns Unauthorized',async()=>{fixture.profile={id:clientId,role:'client',is_active:false};assert.equal((await shareTicketFilesAction(ticketId,[])).error,'Unauthorized.');assert.equal(fixture.atomicAttachCalls.length,0);});
test('share: invalid ticket UUID returns Ticket not found',async()=>{assert.equal((await shareTicketFilesAction('malformed-uuid',[])).error,'Ticket not found.');assert.equal(fixture.atomicAttachCalls.length,0);});
test('share: foreign client returns Ticket not found without RPC',async()=>{fixture.ticket={id:ticketId,client_id:otherClientId};assert.equal((await shareTicketFilesAction(ticketId,[])).error,'Ticket not found.');assert.equal(fixture.atomicAttachCalls.length+fixture.finalized,0);});
test('share: validation failure returns ATTACHMENT_ERROR without RPC',async()=>{assert.equal((await shareTicketFilesAction(ticketId,[entry('bad-key',10)])).error,ATTACHMENT_ERROR);assert.equal(fixture.atomicAttachCalls.length+fixture.finalized,0);});
test('share: successful share calls attach_ticket_files_atomic and revalidates paths',async()=>{fixture.storedObjects.set(tk(),500);assert.deepEqual(await shareTicketFilesAction(ticketId,[entry(tk())]),{});assert.equal(fixture.atomicAttachCalls.length,1);const a=fixture.atomicAttachCalls[0];assert.equal(a.p_actor,clientId);assert.equal(a.p_ticket,ticketId);assert.equal(a.p_entries.length,1);assert.notEqual(a.p_entries[0].key,tk());assert.ok(fixture.revalidated.includes(`/admin/tickets/${ticketId}`));assert.ok(fixture.revalidated.includes(`/portal/tickets/${ticketId}`));});
test('share: Attachment limit reached maps to user-friendly copy',async()=>{fixture.storedObjects.set(tk(),500);fixture.atomicAttachError={message:'Attachment limit reached'};assert.equal((await shareTicketFilesAction(ticketId,[entry(tk())])).error,'A ticket can have at most 10 attachments.');});
test('share: unhandled RPC error stays generic without diagnostics',async()=>{fixture.storedObjects.set(tk(),500);fixture.atomicAttachError={message:'synthetic_db_column_leak_error'};const r=await shareTicketFilesAction(ticketId,[entry(tk())]);assert.equal(r.error,ATTACHMENT_ERROR);assert.ok(!JSON.stringify(r).includes('synthetic_db_column_leak_error'));});
test('createTicketWithAttachmentsAction: validates client session and pending files',async()=>{const k=`private/${clientId}/pending/${fileUuid1}.pdf`;fixture.storedObjects.set(k,1000);await assert.rejects(createTicketWithAttachmentsAction('Subject','Body',[entry(k,1000)]),e=>e.digest==='NEXT_REDIRECT');assert.equal(fixture.redirected,`/portal/tickets/${ticketId}`);assert.equal(fixture.createTicketCalls.length,1);const a=fixture.createTicketCalls[0];assert.equal(a.p_client,clientId);assert.equal(a.p_subject,'Subject');assert.equal(a.p_body,'Body');assert.equal(a.p_entries.length,1);});
test('confirmTicketAttachmentAction: verifies ownership and calls atomic persistence',async()=>{fixture.storedObjects.set(tk(),500);assert.deepEqual(await confirmTicketAttachmentAction({ticketId,entries:[entry(tk())]}),{notice:'Files shared with this ticket.'});assert.equal(fixture.atomicAttachCalls.length,1);assert.ok(fixture.revalidated.includes(`/portal/tickets/${ticketId}`));});
function request(body,origin='https://redwan.work'){return new NextRequest('https://redwan.work/api/uploads/ticket-presign',{method:'POST',headers:{origin,host:'redwan.work','content-type':'application/json'},body:typeof body==='string'?body:JSON.stringify(body)});}
test('route: cross-origin returns 403',async()=>{const r=await ticketPresignPost(request({ticketId:null,files:[file]},'https://evil.test'));assert.equal(r.status,403);assert.equal((await r.json()).error,'Request origin not allowed.');});
test('route: anonymous request returns 401 Unauthorized',async()=>{fixture.session=null;const r=await ticketPresignPost(request({ticketId:null,files:[file]}));assert.equal(r.status,401);assert.equal((await r.json()).error,'Unauthorized.');});
test('route: malformed JSON returns 400',async()=>{const r=await ticketPresignPost(request('not-valid-json'));assert.equal(r.status,400);assert.equal((await r.json()).error,'Invalid request.');});
test('route: valid same-origin presign returns 200 with uploads array',async()=>{const r=await ticketPresignPost(request({ticketId:null,files:[file]}));assert.equal(r.status,200);const v=await r.json();assert.ok(Array.isArray(v.uploads));assert.equal(v.uploads.length,1);assert.ok(v.uploads[0].key.startsWith(`private/${clientId}/pending/`));});
