import assert from 'node:assert/strict';import test from 'node:test';import {registerHooks} from 'node:module';import {EventEmitter} from 'node:events';
const projectId='11111111-1111-4111-8111-111111111111',fileId='22222222-2222-4222-8222-222222222222',f={};globalThis.__archiveState=f;
function resetState(){Object.assign(f,{entries:[],writes:0,marks:0,prepares:0,stored:new Map(),mismatchReadback:false,sourceBytesOverride:null,markArchivedResult:{error:null},prepareCleanupResult:{error:null},recoveryRow:{data:null,error:null},invoicesResult:{count:0,error:null},presignError:false,revalidatedPaths:[],session:{userId:'admin-1',role:'admin'},profile:{role:'admin',is_active:true},immutableFail:false});f.snapshotResult={data:{project:{id:projectId,archived_at:null,name:'Synthetic Project'},milestones:[{id:'ms-1',title:'Milestone 1',amount_cents:5000}],files:[{id:fileId,r2_key:'source/file-1.pdf',filename:'../../unsafe-slip-filename.pdf',size_bytes:3,bucket:'private',kind:'deliverable'}]},error:null};f.projectRow={id:projectId,archived_at:'2026-09-16T12:00:00Z',archive_key:`archive/project_${projectId}/verified_synthetic.zip`};}
class MockZipArchive extends EventEmitter{constructor(){super();this.aborted=false;}append(value,options){f.entries.push({value:Buffer.isBuffer(value)?value:Buffer.from(value),name:options.name});}async finalize(){if(this.aborted)return;this.emit('data',Buffer.from('synthetic-zip-content'));this.emit('end');}abort(){this.aborted=true;}}
globalThis.__MockZipArchive=MockZipArchive;
const stub=names=>names.map(name=>`export async function ${name}(){return {ok:true};}`).join('\n');
// ZIP producer/parser and immutable source are separate service boundaries in
// this suite; actual bytes/parser interoperability is covered by storage tests.
const modules={
 'server-only':'export {};','next/cache':'export function revalidatePath(path){globalThis.__archiveState.revalidatedPaths.push(path);}',
 'archiver':'export const ZipArchive=globalThis.__MockZipArchive;export default function(){return new globalThis.__MockZipArchive();}',
 '@/lib/crm/immutable-upload':'export async function verifyImmutableUpload(){if(globalThis.__archiveState.immutableFail)throw Error("Legacy upload");}',
 '@/lib/crm/recovery-archive':'export function decodeRecoveryArchive(bytes){if(bytes.toString()!=="synthetic-zip-content")throw Error("Unexpected synthetic archive");return new Map();}',
 '@/lib/r2':`export const ARCHIVE_MAX_BYTES=104857600,ASSET_ALLOWED_EXT=['.pdf','.png','.jpg'],ASSET_MAX_BYTES=5242880;export function assetUrl(key){return 'https://assets.example.test/'+key;}export async function deletePublicObject(){return {ok:true};}export function makeAssetKey(name){return 'assets/'+name;}export function makeDeliverableKey(p,f){return 'private/'+p+'/'+f;}export async function presignPrivatePut(){return 'https://presigned.example.test/put';}export async function putPublicObject(){return {ok:true};}export function validateContactFile(){return {ok:true,ext:'pdf'};}export async function putPrivateObject(key,bytes){const f=globalThis.__archiveState;f.writes++;f.stored.set(key,Buffer.from(bytes));}export async function getPrivateObjectBytes(key){const f=globalThis.__archiveState;if(key==='source/file-1.pdf')return f.sourceBytesOverride??Buffer.from('abc');if(f.mismatchReadback)return Buffer.from('corrupted-readback-bytes');return f.stored.get(key)??Buffer.from('default-stored-bytes');}export async function presignPrivateGet(key,ttl){if(globalThis.__archiveState.presignError)throw Error('presign-network-timeout');return 'https://presigned.example.test/'+key+'?ttl='+ttl;}export async function deletePrivateObjects(){return {ok:true};}`,
 '@/lib/supabase/admin':`export function getSupabaseAdmin(){const f=globalThis.__archiveState;return {async rpc(name){if(name==='project_cleanup_snapshot')return f.snapshotResult;if(name==='mark_project_archived'){f.marks++;return f.markArchivedResult;}if(name==='prepare_project_cleanup'){f.prepares++;return f.prepareCleanupResult;}return {data:null,error:null};},from(table){const q={select(){return q;},eq(){return q;},is(){return q;},update(){return q;},delete(){return q;},order(){return q;},limit(){return q;},async maybeSingle(){if(table==='project_recovery')return f.recoveryRow;if(table==='projects')return {data:f.projectRow,error:null};if(table==='profiles')return {data:f.profile,error:null};return {data:null,error:null};},then(a,b){return Promise.resolve(table==='invoices'?f.invoicesResult:{data:[],error:null}).then(a,b);}};return q;}};}`,
 '@/lib/auth/session':'export async function getCurrentSession(){return globalThis.__archiveState.session;}',
 '@/lib/email/recipients':'export async function emailOrigin(){return "https://example.test";}export async function recipientEmail(){return null;}',
 '@/lib/email':'export function queueEmail(){}export async function recordUnsent(){return {ok:true};}export async function sendDeliverableUploadedEmail(){return {ok:true};}',
 '@/lib/crm/clients':stub(['convertLead','inviteClient','setClientActive']),
 '@/lib/crm/tickets':stub(['adminReply','setTicketStatus']),
 '@/lib/crm/files':stub(['createFileRow','deleteOwnedFile']),
 '@/lib/mime':stub(['extFromFilename','isAllowedAssetMime']),
 '@/lib/format':'export function formatBytes(){return "synthetic";}',
 '@/lib/crm/invoices':stub(['addInvoiceItem','confirmPayment','createDraftInvoice','createDraftInvoiceWithItems','deleteInvoiceItem','getInvoiceDetail','rejectPayment','sendInvoice','updateDraftInvoice','updateInvoiceItem','voidInvoice']),
 '@/lib/crm/deliverable-validation':'export async function validateDeliverable(){return null;}',
 '@/lib/crm/milestone-money':'export function parseMilestoneMoney(){return {ok:true,amount_cents:100};}',
};
registerHooks({resolve(s,c,n){if(Object.hasOwn(modules,s))return {url:'data:text/javascript,'+encodeURIComponent(modules[s]),shortCircuit:true};if(s.startsWith('@/lib/'))return {url:new URL('../../'+s.slice(2)+'.ts',import.meta.url).href,shortCircuit:true};return n(s,c);}});
const {archiveProject}=await import('../../lib/crm/verified-archive.ts');const {purgeArchivedProject}=await import('../../lib/crm/retention.ts');const {getArchiveDownloadUrl}=await import('../../lib/crm/projects.ts');const {archiveProjectAction,purgeArchivedProjectAction,archiveDownloadUrlAction}=await import('../../lib/crm/admin-actions.ts');
test('archive preserves manifests but never uses display filenames as ZIP paths',async()=>{resetState();const r=await archiveProject(projectId);assert.equal(r.ok,true);assert.ok(r.archiveKey.startsWith(`archive/project_${projectId}/verified_`));for(const name of ['files/'+fileId,'project.json','milestones.json','files.json','recovery.json'])assert.ok(f.entries.some(e=>e.name===name));assert.ok(f.entries.every(e=>!e.name.includes('..')&&!e.name.includes('unsafe-slip')));assert.equal(f.marks,1);});
test('archive rejects already archived project and invalid UUIDs',async()=>{resetState();f.snapshotResult.data.project.archived_at='2026-09-10T10:00:00Z';const r=await archiveProject(projectId);assert.equal(r.ok,false);assert.equal(r.error,'Project already archived.');assert.equal(f.marks,0);const invalid=await archiveProject('not-a-valid-uuid');assert.equal(invalid.ok,false);assert.equal(invalid.error,'Project not found.');assert.equal(f.marks,0);});
test('archive rejects byte count mismatch between R2 and database record',async()=>{resetState();f.sourceBytesOverride=Buffer.from('12345');const r=await archiveProject(projectId);assert.equal(r.ok,false);assert.equal(r.error,'Archive verification failed. Project and source files are preserved.');assert.equal(f.marks,0);});
test('read-back mismatch prevents project archive transition',async()=>{resetState();f.mismatchReadback=true;const r=await archiveProject(projectId);assert.equal(r.ok,false);assert.equal(f.marks,0);assert.equal(r.error,'Archive verification failed. Project and source files are preserved.');});
test('archive handles concurrent project change during mark_project_archived RPC',async()=>{resetState();f.markArchivedResult={error:{message:'Project changed during archive'}};const r=await archiveProject(projectId);assert.equal(r.ok,false);assert.equal(r.error,'Project changed during archive. Source data is preserved; retry after review.');});
function archived(){resetState();f.snapshotResult.data.project.archived_at='2026-09-10T10:00:00Z';}
test('purge: FINANCIAL RETENTION BLOCKER - refuses purge when linked invoices exist',async()=>{archived();f.invoicesResult={count:2,error:null};const r=await purgeArchivedProject(projectId);assert.equal(r.ok,false);assert.equal(r.error,'Project has retained invoices and cannot be purged.');assert.equal(f.prepares,0);assert.equal(f.writes,0);});
test('purge: financial check failure fails closed',async()=>{archived();f.invoicesResult={count:null,error:{message:'db-connection-failed'}};const r=await purgeArchivedProject(projectId);assert.equal(r.ok,false);assert.equal(r.error,'Financial retention check unavailable.');assert.equal(f.prepares,0);});
test('purge: refuses purge when project is not yet archived',async()=>{resetState();const r=await purgeArchivedProject(projectId);assert.equal(r.ok,false);assert.equal(r.error,'Project is not archived.');assert.equal(f.prepares,0);});
test('purge: idempotent success when recovery record already exists',async()=>{resetState();f.recoveryRow={data:{project_id:projectId},error:null};const r=await purgeArchivedProject(projectId);assert.equal(r.ok,true);assert.equal(f.prepares,0);assert.equal(f.writes,0);});
test('purge: legacy mutable source remains held without creating deletion jobs',async()=>{archived();f.immutableFail=true;const r=await purgeArchivedProject(projectId);assert.equal(r.ok,false);assert.match(r.error,/held/);assert.equal(f.prepares+f.writes,0);});
test('purge: recovery read-back verification failure aborts without deleting source',async()=>{archived();f.mismatchReadback=true;const r=await purgeArchivedProject(projectId);assert.equal(r.ok,false);assert.equal(r.error,'Could not verify recovery backup. Project and source files were not purged.');assert.equal(f.prepares,0);});
test('purge: atomic database cleanup queues deletions and cascades project',async()=>{archived();const r=await purgeArchivedProject(projectId);assert.equal(r.ok,true);assert.equal(f.prepares,1);assert.equal(f.writes,1);});
test('purge: database RPC retained invoices conflict mapping',async()=>{archived();f.prepareCleanupResult={error:{message:'Project has retained invoices'}};const r=await purgeArchivedProject(projectId);assert.equal(r.ok,false);assert.equal(r.error,'Project has retained invoices and cannot be purged.');});
test('download: getArchiveDownloadUrl generates presigned URL for archived project',async()=>{resetState();const r=await getArchiveDownloadUrl(projectId);assert.equal(r.ok,true);assert.ok(r.url.startsWith('https://presigned.example.test/archive/project_'));});
test('download: getArchiveDownloadUrl refuses unarchived or missing projects',async()=>{resetState();f.projectRow.archive_key=null;const a=await getArchiveDownloadUrl(projectId);assert.equal(a.ok,false);assert.equal(a.error,'Project is not archived.');f.projectRow.archived_at=null;const b=await getArchiveDownloadUrl(projectId);assert.equal(b.ok,false);assert.equal(b.error,'Project is not archived.');f.projectRow=null;const c=await getArchiveDownloadUrl(projectId);assert.equal(c.ok,false);assert.equal(c.error,'Project not found.');});
test('download: getArchiveDownloadUrl masks presigning errors',async()=>{resetState();f.presignError=true;const r=await getArchiveDownloadUrl(projectId);assert.equal(r.ok,false);assert.equal(r.error,'Archive download unavailable.');assert.equal(r.error.includes('presign-network-timeout'),false);});
test('admin actions: archiveProjectAction, purgeArchivedProjectAction, and archiveDownloadUrlAction enforce admin authority',async()=>{resetState();for(const [session,profile]of [[{userId:'client-1',role:'client'},{role:'client',is_active:true}],[{userId:'admin-1',role:'admin'},{role:'admin',is_active:false}]]){f.session=session;f.profile=profile;assert.deepEqual(await archiveProjectAction(projectId),{error:'Unauthorized.'});assert.deepEqual(await purgeArchivedProjectAction(projectId),{error:'Unauthorized.'});assert.deepEqual(await archiveDownloadUrlAction(projectId),{ok:false,error:'Unauthorized.'});}f.session={userId:'admin-1',role:'admin'};f.profile={role:'admin',is_active:true};assert.match((await archiveProjectAction(projectId)).notice,/Project archived with a verified backup/);assert.ok(f.revalidatedPaths.includes('/admin/projects'));assert.ok(f.revalidatedPaths.includes('/admin'));f.revalidatedPaths=[];f.snapshotResult.data.project.archived_at='2026-09-10T10:00:00Z';assert.deepEqual(await purgeArchivedProjectAction(projectId),{});assert.ok(f.revalidatedPaths.includes('/admin/projects'));assert.ok(f.revalidatedPaths.includes('/admin'));const dl=await archiveDownloadUrlAction(projectId);assert.equal(dl.ok,true);assert.ok(dl.url.includes('archive/project_'));});
