import Link from 'next/link';
import {redirect} from 'next/navigation';
import {Card,CardContent,CardHeader,CardTitle} from '@/components/ui/card';
import {Badge} from '@/components/ui/badge';
import {workflowSession} from '@/lib/crm/workflow-access';
import {getSupabaseAdmin} from '@/lib/supabase/admin';
export const dynamic='force-dynamic';
type Dashboard={openTickets:number;activeProjects:number;outstandingInvoices:number;projects:Array<{id:string;name:string;status:string}>;tickets:Array<{id:string;number:number;subject:string;status:string}>};
export default async function PortalDashboardPage(){
 const session=await workflowSession('client');if(!session)redirect('/login?next=/portal');
 const {data,error}=await getSupabaseAdmin().rpc('portal_dashboard',{p_actor:session.userId});if(error||!data)throw new Error('Could not load dashboard.');const dashboard=data as Dashboard;
 return <div className="space-y-6"><h1 className="text-2xl font-semibold">Dashboard</h1><div className="grid gap-4 sm:grid-cols-3">{[{title:'Open tickets',value:dashboard.openTickets,href:'/portal/tickets',text:'Awaiting a reply from support'},{title:'Active projects',value:dashboard.activeProjects,href:'/portal/projects',text:'View projects'},{title:'Outstanding invoices',value:dashboard.outstandingInvoices,href:'/portal/invoices',text:'View invoices'}].map(card=><Card key={card.title}><CardHeader><CardTitle className="text-sm font-medium text-muted-foreground">{card.title}</CardTitle></CardHeader><CardContent><p className="text-3xl font-semibold">{card.value}</p><Link href={card.href} className="mt-1 block text-xs text-muted-foreground underline">{card.text}</Link></CardContent></Card>)}</div>
 <section className="space-y-3"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Projects</h2><Link className="text-sm underline" href="/portal/projects">View all</Link></div>{!dashboard.projects.length?<p className="text-sm text-muted-foreground">No projects yet.</p>:<ul className="rounded-lg border">{dashboard.projects.map(project=><li key={project.id} className="flex items-center justify-between gap-3 border-t p-3 first:border-t-0"><Link href={`/portal/projects/${project.id}`} className="min-w-0 break-words underline">{project.name}</Link><Badge variant="outline">{project.status}</Badge></li>)}</ul>}</section>
 <section className="space-y-3"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Recent tickets</h2><Link className="text-sm underline" href="/portal/tickets">View all</Link></div>{!dashboard.tickets.length?<p className="text-sm text-muted-foreground">No tickets yet.</p>:<ul className="rounded-lg border">{dashboard.tickets.map(ticket=><li key={ticket.id} className="flex flex-wrap items-center justify-between gap-3 border-t p-3 first:border-t-0"><span className="font-mono text-xs">TKT-{ticket.number}</span><Link className="min-w-0 flex-1 break-words underline" href={`/portal/tickets/${ticket.id}`}>{ticket.subject}</Link><Badge variant="outline">{ticket.status.replaceAll('_',' ')}</Badge></li>)}</ul>}</section></div>;
}
