import Link from 'next/link';
import { Badge } from '@/components/ui/badge';
import { listInvoices, type InvoiceStatus } from '@/lib/crm/invoices';
import { money } from '@/components/admin/invoice-forms';

export const dynamic = 'force-dynamic';
const statuses: Array<InvoiceStatus | undefined> = [undefined, 'draft', 'sent', 'paid', 'void'];
function date(value: string | null) { return value ? new Date(`${value.slice(0, 10)}T00:00:00Z`).toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric', timeZone: 'UTC' }) : '—'; }
export default async function AdminInvoicesPage({ searchParams }: { searchParams: Promise<{ status?: string }> }) { const query = await searchParams; const status = statuses.includes(query.status as InvoiceStatus) ? query.status as InvoiceStatus | undefined : undefined; const [invoices] = await Promise.all([listInvoices({ userId: '', role: 'admin' }, status)]); return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-2xl font-semibold">Invoices</h1><Link href="/admin/invoices/new" className="inline-flex h-9 items-center rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground">New invoice</Link></div><nav aria-label="Invoice status filters" className="flex flex-wrap gap-2">{statuses.map((value) => <Link key={value ?? 'all'} href={value ? `/admin/invoices?status=${value}` : '/admin/invoices'} className={`rounded-md border px-3 py-1.5 text-sm ${status === value ? 'bg-accent font-medium' : 'hover:bg-accent'}`}>{value ? value[0].toUpperCase() + value.slice(1) : 'All'}</Link>)}</nav>{invoices.length === 0 ? <p className="text-sm text-muted-foreground">No invoices in this view.</p> : <div className="overflow-x-auto rounded-lg border"><table className="w-full min-w-[720px] text-sm"><thead className="bg-muted/50 text-left text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="px-4 py-2 font-medium">Invoice</th><th className="px-4 py-2 font-medium">Client</th><th className="px-4 py-2 font-medium">Project</th><th className="px-4 py-2 text-right font-medium">Total</th><th className="px-4 py-2 text-right font-medium">Outstanding</th><th className="px-4 py-2 font-medium">Status</th><th className="px-4 py-2 font-medium">Due</th></tr></thead><tbody>{invoices.map((invoice) => <tr key={invoice.id} className="border-t"><td className="px-4 py-2 font-mono text-xs"><Link href={`/admin/invoices/${invoice.id}`} className="hover:underline">INV-{invoice.number}</Link></td><td className="px-4 py-2">{invoice.client_name ?? invoice.client_email}</td><td className="px-4 py-2">{invoice.project_name}</td><td className="px-4 py-2 text-right">{money(invoice.total_cents, invoice.currency)}</td><td className="px-4 py-2 text-right">{money(invoice.outstanding_cents, invoice.currency)}</td><td className="px-4 py-2"><Badge variant="outline">{invoice.status}</Badge></td><td className="px-4 py-2 text-muted-foreground">{date(invoice.due_at)}</td></tr>)}</tbody></table></div>}</div>; }
