import Link from 'next/link';
import {redirect,notFound} from 'next/navigation';
import {Badge} from '@/components/ui/badge';
import {workflowSession,workflowPage} from '@/lib/crm/workflow-access';
import {getSupabaseAdmin} from '@/lib/supabase/admin';
import {validUuid} from '@/lib/crm/attachments';
import {formatBytes} from '@/lib/format';
export const dynamic='force-dynamic';
type Group={id:string;name:string;status:string;due_at:string|null;file_total:number;files:Array<{id:string;filename:string;size_bytes:number;created_at:string}>};
export default async function PortalFilesPage({searchParams}:{searchParams:Promise<{page?:string;project?:string}>}){
 const session=await workflowSession('client');if(!session)redirect('/login?next=/portal/files');const params=await searchParams,page=workflowPage(params.page),project=params.project??null;if(project&&!validUuid(project))notFound();
 const {data,error}=await getSupabaseAdmin().rpc('portal_files_page',{p_actor:session.userId,p_project:project,p_page:page});if(error||!data)throw new Error('Could not load files.');const groups=data.items as Group[];if(project&&!groups.length)notFound();const size=project?25:10;const href=(p:number)=>`?page=${p}${project?`&project=${project}`:''}`;
 return <div className="space-y-6"><h1 className="text-2xl font-semibold">Files</h1>{project&&<Link className="underline" href="/portal/files">All projects</Link>}{!groups.length?<p className="text-sm text-muted-foreground">No deliverables yet.</p>:groups.map(group=><section key={group.id} className="space-y-3 rounded-lg border p-4"><div className="flex flex-wrap items-center gap-3"><h2 className="text-base font-semibold">{group.name}</h2><Badge variant="outline">{group.status}</Badge><span className="text-xs text-muted-foreground">Due {group.due_at??'Not set'}</span></div>{!group.files.length?<p className="text-sm text-muted-foreground">No files on this page.</p>:<div className="overflow-x-auto rounded-lg border"><table className="w-full min-w-[520px] text-sm"><thead className="bg-muted/50 text-left"><tr><th className="p-3">File</th><th className="p-3">Size</th><th className="p-3">Uploaded</th><th className="p-3">Actions</th></tr></thead><tbody>{group.files.map(file=><tr key={file.id} className="border-t"><td className="p-3">{file.filename}</td><td className="p-3">{formatBytes(Number(file.size_bytes))}</td><td className="p-3">{file.created_at.slice(0,10)}</td><td className="p-3"><a className="inline-flex rounded-md border px-3 py-1 text-xs" href={`/api/files/${file.id}/download`}>Download</a></td></tr>)}</tbody></table></div>}{!project&&group.file_total>10&&<Link className="inline-block text-sm underline" href={`?project=${group.id}&page=1`}>Browse all {group.file_total} files</Link>}</section>)}<nav aria-label={project?'File pages':'Project file groups'} className="flex gap-4">{page>1&&<Link href={href(page-1)}>Previous</Link>}{Number(data.total)>page*size&&<Link href={href(page+1)}>Next</Link>}</nav></div>;
}
