'use client';
import {useRef,useState,useTransition} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {Printer} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle,DialogTrigger} from '@/components/ui/dialog';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Textarea} from '@/components/ui/textarea';
import {addInvoiceItemAction,confirmPaymentAction,createDraftInvoiceWithItemsAction,deleteInvoiceItemAction,rejectPaymentAction,sendInvoiceAction,updateDraftInvoiceAction,updateInvoiceItemAction,voidInvoiceAction} from '@/lib/crm/admin-actions';
import {calculateInvoiceTotalCents,displayInvoiceLineCents,displayInvoiceTotalCents,isSafeInvoiceLine,MAX_INVOICE_UNIT_PRICE_CENTS} from '@/lib/crm/invoice-math';
import type {InvoiceItemRow,PaymentRow} from '@/lib/crm/invoices';
const SEND_NOTICE='Sending locks the invoice financial fields, makes it visible to the client, and queues an email notification. Delivery is tracked separately.';
export function money(cents:number,currency:string){try{return new Intl.NumberFormat('en-US',{style:'currency',currency}).format(cents/100);}catch{return `${(cents/100).toFixed(2)} ${currency}`;}}
export function PrintInvoiceButton(){return <Button type="button" size="sm" variant="outline" className="print:hidden" onClick={()=>window.print()}><Printer className="mr-1.5 size-3.5"/>Print</Button>;}
function cents(value:string){const number=Number(value);return Number.isFinite(number)&&number>=0&&number<=MAX_INVOICE_UNIT_PRICE_CENTS/100?Math.round(number*100):-1;}
type ProjectOption={id:string;name:string;client_name:string|null;client_email:string};
export function NewInvoiceForm({projects}:{projects:ProjectOption[]}){
 const [error,setError]=useState<string|null>(null),[pending,start]=useTransition(),[items,setItems]=useState([{description:'',qty:'1',unit_price:''}]),[currency,setCurrency]=useState('USD'),[sendOpen,setSendOpen]=useState(false),[createdId,setCreatedId]=useState<string|null>(null);
 const router=useRouter(),formRef=useRef<HTMLFormElement>(null),createdRef=useRef<string|null>(null);
 function submit(data:FormData,shouldSend:boolean){
  if(pending)return;setError(null);
  if(createdRef.current){setError('A draft was already created. Open it below to continue without creating a duplicate.');return;}
  if(items.some(item=>!item.description.trim()||!item.unit_price.trim()||!isSafeInvoiceLine(item.qty, cents(item.unit_price)))){setError('Complete every line item with a positive quantity and a valid price.');return;}
  try{calculateInvoiceTotalCents(items.map(item=>({qty:item.qty,unit_price_cents:cents(item.unit_price)})));}catch{setError('Invoice amount exceeds the supported limit.');return;}
  start(async()=>{try{
   const result=await createDraftInvoiceWithItemsAction({project_id:String(data.get('project_id')),currency:String(data.get('currency')||'USD'),due_at:String(data.get('due_at')||'')||null,payment_note:String(data.get('payment_note')||'')||null,items:items.map((item,position)=>({description:item.description.trim(),qty:Number(item.qty),unit_price_cents:cents(item.unit_price),position}))});
   if(result.error||!result.invoiceId){setError(result.error??'Draft could not be created.');return;}
   createdRef.current=result.invoiceId;setCreatedId(result.invoiceId);
   if(shouldSend){const sent=await sendInvoiceAction(result.invoiceId);if(sent.error){setError('Draft saved, but sending failed. Open the saved draft below to retry.');return;}}
   router.push(`/admin/invoices/${result.invoiceId}`);
  }catch{setError(createdRef.current?'Draft saved. Open it below to check whether sending completed.':'Request interrupted. Check the invoice list before retrying.');}});
 }
 return <form ref={formRef} action={data=>submit(data,false)} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-1.5 sm:col-span-2"><Label htmlFor="invoice-project">Project</Label><select id="invoice-project" name="project_id" required disabled={pending||!!createdId} defaultValue={projects.length===1?projects[0].id:''} className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"><option value="">Select an active project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name} | {p.client_name??p.client_email}</option>)}</select></div><div className="space-y-1.5"><Label htmlFor="invoice-currency">Currency</Label><Input id="invoice-currency" name="currency" value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase())} maxLength={3} required disabled={pending||!!createdId}/></div><div className="space-y-1.5"><Label htmlFor="invoice-due">Due date</Label><Input id="invoice-due" name="due_at" type="date" disabled={pending||!!createdId}/></div></div><div className="space-y-1.5"><Label htmlFor="invoice-note">Payment note</Label><Textarea id="invoice-note" name="payment_note" rows={3} maxLength={5000} disabled={pending||!!createdId}/></div>
 <fieldset className="space-y-3" disabled={pending||!!createdId}><legend className="text-sm font-medium">Line items</legend>{items.map((item,index)=><div key={index} className="grid gap-2 sm:grid-cols-[1fr_100px_130px_100px_auto]"><div className="space-y-1"><Label htmlFor={`new-description-${index}`}>Description</Label><Input id={`new-description-${index}`} value={item.description} onChange={e=>setItems(rows=>rows.map((row,i)=>i===index?{...row,description:e.target.value}:row))} required maxLength={500}/></div><div className="space-y-1"><Label htmlFor={`new-qty-${index}`}>Qty</Label><Input id={`new-qty-${index}`} value={item.qty} onChange={e=>setItems(rows=>rows.map((row,i)=>i===index?{...row,qty:e.target.value}:row))} type="number" step="0.001" min="0.001" required/></div><div className="space-y-1"><Label htmlFor={`new-price-${index}`}>Unit price</Label><Input id={`new-price-${index}`} value={item.unit_price} onChange={e=>setItems(rows=>rows.map((row,i)=>i===index?{...row,unit_price:e.target.value}:row))} type="number" step="0.01" min="0" required/></div><div className="flex items-end text-sm">{(()=>{const amount=displayInvoiceLineCents(item.qty,cents(item.unit_price));return amount===null?'Invalid':money(amount,currency);})()}</div><Button type="button" size="sm" variant="ghost" disabled={items.length===1} onClick={()=>setItems(rows=>rows.filter((_,i)=>i!==index))}>Remove</Button></div>)}<p className="text-right text-sm font-semibold">Total: {(()=>{const total=displayInvoiceTotalCents(items.map(item=>({qty:item.qty,unit_price_cents:cents(item.unit_price)})));return total===null?'Invalid':money(total,currency);})()}</p><Button type="button" size="sm" variant="outline" onClick={()=>setItems(rows=>[...rows,{description:'',qty:'1',unit_price:''}])}>Add line item</Button></fieldset>
 {error&&<p role="alert" className="text-sm text-destructive">{error}</p>}{createdId&&<Link className="block underline" href={`/admin/invoices/${createdId}`}>Open saved invoice</Link>}
 <div className="flex flex-wrap gap-2"><Button type="submit" disabled={pending||!!createdId}>{pending?'Saving...':'Save draft'}</Button><Dialog open={sendOpen} onOpenChange={setSendOpen}><DialogTrigger asChild><Button type="button" variant="outline" disabled={pending||!!createdId}>Save and send</Button></DialogTrigger><DialogContent className="max-w-sm"><DialogHeader><DialogTitle>Send invoice</DialogTitle><DialogDescription>{SEND_NOTICE}</DialogDescription></DialogHeader><DialogFooter><Button type="button" variant="ghost" onClick={()=>setSendOpen(false)}>Cancel</Button><Button type="button" disabled={pending||!!createdId} onClick={()=>{setSendOpen(false);if(formRef.current?.reportValidity())submit(new FormData(formRef.current),true);}}>Confirm send</Button></DialogFooter></DialogContent></Dialog></div></form>;
}
export function DraftInvoiceForm({invoice,projects}:{invoice:{id:string;project_id:string;currency:string;due_at:string|null;payment_note:string|null};items:InvoiceItemRow[];projects:ProjectOption[]}){
 const [error,setError]=useState<string|null>(null),[pending,start]=useTransition();const router=useRouter();
 return <form className="space-y-3 print:hidden" action={data=>{setError(null);start(async()=>{const result=await updateDraftInvoiceAction(invoice.id,{project_id:String(data.get('project_id')),currency:String(data.get('currency')),due_at:String(data.get('due_at')||'')||null,payment_note:String(data.get('payment_note')||'')||null});if(result.error)setError(result.error);else router.refresh();});}}><div className="grid gap-3 sm:grid-cols-3"><div className="space-y-1.5 sm:col-span-2"><Label htmlFor="draft-project">Project</Label><select id="draft-project" name="project_id" defaultValue={invoice.project_id} required className="flex h-10 w-full rounded-md border bg-background px-3 py-2 text-sm">{projects.map(p=><option key={p.id} value={p.id}>{p.name} | {p.client_name??p.client_email}</option>)}</select></div><div className="space-y-1.5"><Label htmlFor="draft-currency">Currency</Label><Input id="draft-currency" name="currency" defaultValue={invoice.currency} maxLength={3} required/></div><div className="space-y-1.5"><Label htmlFor="draft-due">Due date</Label><Input id="draft-due" name="due_at" type="date" defaultValue={invoice.due_at??''}/></div></div><div className="space-y-1.5"><Label htmlFor="draft-note">Payment note</Label><Textarea id="draft-note" name="payment_note" defaultValue={invoice.payment_note??''} maxLength={5000}/></div>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<Button size="sm" disabled={pending}>{pending?'Saving...':'Save changes'}</Button></form>;
}
export function LineItemForm({invoiceId,item,position=0}:{invoiceId:string;item?:InvoiceItemRow;position?:number}){
 const [error,setError]=useState<string|null>(null),[pending,start]=useTransition();const router=useRouter();const suffix=item?.id??position;
 return <form className="grid gap-2 sm:grid-cols-[1fr_100px_130px_auto] sm:items-end" action={form=>{setError(null);start(async()=>{const data={description:String(form.get('description')),qty:Number(form.get('qty')),unit_price_cents:cents(String(form.get('unit_price'))),position};const result=item?await updateInvoiceItemAction(item.id,data):await addInvoiceItemAction(invoiceId,data);if(result.error)setError(result.error);else router.refresh();});}}><div><Label htmlFor={`description-${suffix}`}>Description</Label><Input id={`description-${suffix}`} name="description" defaultValue={item?.description} required maxLength={500}/></div><div><Label htmlFor={`qty-${suffix}`}>Qty</Label><Input id={`qty-${suffix}`} name="qty" type="number" step="0.001" min="0.001" defaultValue={item?.qty??1} required/></div><div><Label htmlFor={`price-${suffix}`}>Unit price</Label><Input id={`price-${suffix}`} name="unit_price" type="number" step="0.01" min="0" defaultValue={item?(item.unit_price_cents/100).toFixed(2):''} required/></div><Button size="sm" disabled={pending}>{pending?'Saving...':item?'Update':'Add item'}</Button>{error&&<p role="alert" className="text-xs text-destructive sm:col-span-full">{error}</p>}</form>;
}
export function DeleteItemButton({itemId}:{itemId:string}){const [error,setError]=useState<string|null>(null),[pending,start]=useTransition();const router=useRouter();return <span className="inline-flex items-center gap-2">{error&&<span role="alert" className="text-xs text-destructive">{error}</span>}<Button type="button" size="sm" variant="ghost" disabled={pending} onClick={()=>start(async()=>{const result=await deleteInvoiceItemAction(itemId);if(result.error)setError(result.error);else router.refresh();})}>{pending?'Removing...':'Remove'}</Button></span>;}
export function InvoiceLifecycleControls({invoiceId,number,status}:{invoiceId:string;number:number;status:string}){
 const [open,setOpen]=useState(false),[typed,setTyped]=useState(''),[error,setError]=useState<string|null>(null),[pending,start]=useTransition();const router=useRouter();
 function run(action:()=>Promise<{error?:string}>){setError(null);start(async()=>{const result=await action();if(result.error)setError(result.error);else{setOpen(false);setTyped('');router.refresh();}});}
 if(status!=='draft'&&status!=='sent')return null;const sending=status==='draft';
 return <div className="print:hidden"><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm" variant={sending?'default':'destructive'}>{sending?'Send invoice':'Void invoice'}</Button></DialogTrigger><DialogContent className="max-w-sm"><DialogHeader><DialogTitle>{sending?'Send invoice':'Void invoice'}</DialogTitle><DialogDescription>{sending?SEND_NOTICE:`Type INV-${number} to confirm. This preserves the invoice for audit.`}</DialogDescription></DialogHeader>{!sending&&<><Label htmlFor={`void-${invoiceId}`}>Invoice reference</Label><Input id={`void-${invoiceId}`} value={typed} onChange={e=>setTyped(e.target.value)} placeholder={`INV-${number}`} autoComplete="off"/></>}{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<DialogFooter><Button variant="ghost" onClick={()=>setOpen(false)}>Cancel</Button><Button variant={sending?'default':'destructive'} disabled={pending||(!sending&&typed!==`INV-${number}`)} onClick={()=>run(()=>sending?sendInvoiceAction(invoiceId):voidInvoiceAction(invoiceId))}>{pending?'Working...':sending?'Confirm send':'Confirm void'}</Button></DialogFooter></DialogContent></Dialog></div>;
}
export function PaymentDecisionButtons({payment}:{payment:PaymentRow}){const [error,setError]=useState<string|null>(null),[pending,start]=useTransition();const router=useRouter();function decide(action:(id:string)=>Promise<{error?:string}>){setError(null);start(async()=>{const result=await action(payment.id);if(result.error)setError(result.error);else router.refresh();});}return payment.status==='submitted'?<span className="inline-flex flex-wrap items-center gap-2 print:hidden"><Button size="sm" disabled={pending} onClick={()=>decide(confirmPaymentAction)}>Confirm</Button><Button size="sm" variant="outline" disabled={pending} onClick={()=>decide(rejectPaymentAction)}>Reject</Button>{error&&<span role="alert" className="text-xs text-destructive">{error}</span>}</span>:<span className="text-xs text-muted-foreground">{payment.status}</span>;}
