import Link from 'next/link';
import {notFound} from 'next/navigation';
import {Badge} from '@/components/ui/badge';
import {getInvoiceDetail} from '@/lib/crm/invoices';
import {roundInvoiceLineCents} from '@/lib/crm/invoice-math';
import {listProjects} from '@/lib/crm/projects';
import {workflowSession} from '@/lib/crm/workflow-access';
import {DeleteItemButton,DraftInvoiceForm,InvoiceLifecycleControls,LineItemForm,PaymentDecisionButtons,PrintInvoiceButton} from '@/components/admin/invoice-forms';
export const dynamic='force-dynamic';
// A Server Component must not invoke a function exported from a use-client module.
function money(cents:number,currency:string){try{return new Intl.NumberFormat('en-US',{style:'currency',currency}).format(Number(cents)/100);}catch{return `${(Number(cents)/100).toFixed(2)} ${currency}`;}}
function date(value:string|null){return value?new Date(value).toLocaleDateString('en-US',{year:'numeric',month:'short',day:'numeric',timeZone:'UTC'}):'Not set';}
export default async function AdminInvoiceDetailPage({params}:{params:Promise<{id:string}>}) {
 const session=await workflowSession('admin');if(!session)notFound();
 const {id}=await params;const result=await getInvoiceDetail(id,{userId:session.userId,role:'admin'});if(!result.ok)notFound();
 const {invoice,items,payments}=result;const draft=invoice.status==='draft';
 const projects=draft?(await listProjects({archived:false})).filter(project=>project.status==='active'):[];
 return <div className="space-y-6"><Link className="text-sm underline print:hidden" href="/admin/invoices">All invoices</Link><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-mono text-xs">INV-{invoice.number}</p><h1 className="text-2xl font-semibold">{invoice.project_name}</h1><p className="mt-1 text-sm text-muted-foreground">{invoice.client_name??invoice.client_email} | {invoice.client_email}</p></div><div className="flex flex-wrap items-center gap-3"><Badge variant="outline">{invoice.status}</Badge><PrintInvoiceButton/><InvoiceLifecycleControls invoiceId={invoice.id} number={invoice.number} status={invoice.status}/></div></header>
 <div className="space-y-6"><section className="grid gap-4 sm:grid-cols-3"><div><p className="text-xs uppercase text-muted-foreground">Issued</p><p>{date(invoice.issued_at)}</p></div><div><p className="text-xs uppercase text-muted-foreground">Due</p><p>{date(invoice.due_at)}</p></div><div><p className="text-xs uppercase text-muted-foreground">Currency</p><p>{invoice.currency}</p></div></section>
 {draft&&<DraftInvoiceForm invoice={invoice} items={items} projects={projects.map(project=>({id:project.id,name:project.name,client_name:project.client_name,client_email:project.client_email}))}/>}
 <section className="space-y-3"><h2 className="text-lg font-semibold">Line items</h2><div className="overflow-x-auto rounded-lg border"><table className="w-full text-sm"><thead className="bg-muted/50 text-left"><tr><th className="p-3">Description</th><th className="p-3 text-right">Qty</th><th className="p-3 text-right">Unit price</th><th className="p-3 text-right">Amount</th><th className="p-3 print:hidden" aria-label="Actions"/></tr></thead><tbody>{items.map(item=><tr key={item.id} className="border-t"><td className="p-3">{item.description}</td><td className="p-3 text-right">{item.qty}</td><td className="p-3 text-right">{money(item.unit_price_cents,invoice.currency)}</td><td className="p-3 text-right">{money(roundInvoiceLineCents(item.qty,item.unit_price_cents),invoice.currency)}</td><td className="p-3 print:hidden">{draft&&<DeleteItemButton itemId={item.id}/>}</td></tr>)}</tbody></table></div>{draft&&<div className="space-y-3 print:hidden">{items.map(item=><LineItemForm key={item.id} invoiceId={invoice.id} item={item} position={item.position}/>)}<LineItemForm invoiceId={invoice.id} position={items.length}/></div>}</section>
 <section className="ml-auto max-w-sm space-y-2 border-t pt-4 text-sm">{[['Total',invoice.total_cents],['Submitted',invoice.submitted_cents],['Confirmed',invoice.confirmed_cents],['Outstanding',invoice.outstanding_cents]].map(([label,value])=><div key={String(label)} className="flex justify-between"><span>{label}</span><strong>{money(Number(value),invoice.currency)}</strong></div>)}</section>
 {invoice.payment_note&&<section><h2 className="text-lg font-semibold">Payment note</h2><p className="mt-2 whitespace-pre-wrap text-sm">{invoice.payment_note}</p></section>}
 <section><h2 className="mb-3 text-lg font-semibold">Payment history</h2>{!payments.length?<p className="text-sm text-muted-foreground">No payments submitted.</p>:<div className="overflow-x-auto rounded-lg border"><table className="w-full text-sm"><thead className="bg-muted/50 text-left"><tr>{['Date','Method','Reference','Amount','Status','Action'].map(label=><th key={label} className={`p-3 ${label==='Action'?'print:hidden':''}`}>{label}</th>)}</tr></thead><tbody>{payments.map(payment=><tr key={payment.id} className="border-t"><td className="p-3">{date(payment.created_at)}</td><td className="p-3">{payment.method}</td><td className="p-3 font-mono text-xs">{payment.reference}</td><td className="p-3">{money(payment.amount_cents,invoice.currency)}</td><td className="p-3">{payment.status}</td><td className="p-3 print:hidden">{invoice.status==='sent'&&<PaymentDecisionButtons payment={payment}/>}</td></tr>)}</tbody></table></div>}</section></div></div>;
}
