'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Card,CardContent,CardHeader,CardTitle} from '@/components/ui/card';
import {Label} from '@/components/ui/label';
type Backup={file_id?:string;project_id?:string;name:string;created_at:string};
type Catalog={files:Backup[];projects:Backup[];hasNext:boolean};
type Preview={id:string;kind:string;name:string;files:number;notice:string};
async function call(action:string,fields:Record<string,unknown>){const response=await fetch('/api/recovery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...fields}),cache:'no-store'});const value=await response.json();if(!response.ok)throw new Error(value.error||'Recovery request failed.');return value;}
export default function RecoveryPage(){
 const [catalog,setCatalog]=useState<Catalog|null>(null),[page,setPage]=useState(1),[error,setError]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState<Preview|null>(null),[selected,setSelected]=useState<File|null>(null),[confirm,setConfirm]=useState(false),[projectLink,setProjectLink]=useState<string|null>(null);
 const lock=useRef(false),input=useRef<HTMLInputElement>(null);
 useEffect(()=>{const controller=new AbortController();setCatalog(null);fetch(`/api/recovery?page=${page}`,{cache:'no-store',signal:controller.signal}).then(async r=>{const v=await r.json();if(!r.ok)throw new Error(v.error||'Backup listing unavailable.');setCatalog(v);}).catch(e=>{if(e.name!=='AbortError')setError('Backup listing unavailable. Check admin access and refresh.');});return()=>controller.abort();},[page]);
 async function run(work:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await work();}catch(e){setError(e instanceof Error?e.message:'Recovery request failed.');}finally{lock.current=false;setBusy(false);}}
 async function upload(){await run(async()=>{if(!selected||selected.size<22||selected.size>100*1024*1024)throw new Error('Choose a registered backup ZIP up to 100 MB.');setPreview(null);setConfirm(false);setProjectLink(null);setStatus('Preparing private upload...');const prepared=await call('upload',{size:selected.size});setStatus('Uploading directly to private storage...');const put=await fetch(prepared.url,{method:'PUT',headers:{'Content-Type':'application/zip'},body:selected});if(!put.ok)throw new Error('Upload failed or expired. Choose the file and retry; no restore was performed.');setStatus('Validating and sealing backup bytes...');const p=await call('preview',{id:prepared.id});setPreview(p);setStatus('Backup verified. Review the scope before restoring.');});}
 async function restore(){await run(async()=>{if(!preview||!confirm)return;setStatus('Restoring and verifying files...');const restored=await call('restore',{id:preview.id});setStatus('Restore completed. Existing data was not overwritten; the backup remains retained.');if(restored.result?.projectId)setProjectLink(`/admin/projects/${restored.result.projectId}`);setPreview(null);setConfirm(false);setSelected(null);if(input.current)input.current.value='';});}
 async function download(item:Backup,kind:string){await run(async()=>{const response=await fetch(`/api/recovery?kind=${kind}&id=${item.file_id??item.project_id}`,{cache:'no-store'});const value=await response.json();if(!response.ok)throw new Error(value.error||'Backup unavailable.');const link=document.createElement('a');link.href=value.url;link.rel='noreferrer';link.referrerPolicy='no-referrer';link.download='recovery.zip';document.body.appendChild(link);link.click();link.remove();setStatus('Direct download started. The private link expires shortly.');});}
 return <main className="mx-auto max-w-4xl space-y-6 p-4 sm:p-6"><div><h1 className="text-2xl font-semibold">Backup recovery</h1><p className="mt-2 text-sm text-muted-foreground">Private backups are retained without automatic expiry. Download a backup, then upload the same unmodified ZIP if you need to restore it.</p><Link href="/admin/projects" className="text-sm underline">Back to projects</Link></div>
 {error&&<p role="alert" className="break-words text-sm text-destructive">{error}</p>}<p role="status" aria-live="polite" className="text-sm">{status}</p>
 <Card><CardHeader><CardTitle>Restore a local backup</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm">Only registered individual-file and purged-project backups are supported. Project restores create a new project for its existing client; individual restores require the original parent. No accounts or invoice history are recreated.</p><Label htmlFor="recovery-file">Backup ZIP (maximum 100 MB)</Label><input ref={input} id="recovery-file" type="file" accept=".zip,application/zip" disabled={busy} className="block w-full max-w-full text-sm" onChange={e=>{setSelected(e.target.files?.[0]??null);setPreview(null);setConfirm(false);}}/><Button onClick={upload} disabled={busy||!selected}>{busy?'Working...':'Upload and preview'}</Button>
 {preview&&<section aria-label="Restore preview" className="space-y-3 rounded border p-4"><h2 className="break-words font-semibold">{preview.name}</h2><p>{preview.kind==='project'?'Project':'Individual file'} backup: {preview.files} file(s)</p><p className="text-sm">{preview.notice}</p><label className="flex items-start gap-2"><input type="checkbox" checked={confirm} disabled={busy} onChange={e=>setConfirm(e.target.checked)}/><span className="text-sm">I confirm restoring this backup with new file identifiers and storage keys.</span></label><div className="flex flex-wrap gap-2"><Button onClick={restore} disabled={busy||!confirm}>Confirm restore</Button><Button variant="outline" disabled={busy} onClick={()=>{setPreview(null);setConfirm(false);setStatus('Restore cancelled. Uploaded staging data remains private; no source data changed.');}}>Cancel</Button></div></section>}
 {projectLink&&<Link className="block underline" href={projectLink}>Open restored project</Link>}</CardContent></Card>
 <Card><CardHeader><CardTitle>Retained backups</CardTitle></CardHeader><CardContent className="space-y-4">{!catalog?<p>Loading backups...</p>:<>{catalog.files.length+catalog.projects.length===0&&<p>No registered backups on this page.</p>}{(['individual','project'] as const).map(kind=><section key={kind}><h2 className="mb-2 font-semibold">{kind==='individual'?'Individual files':'Purged projects'}</h2><ul className="space-y-2">{(kind==='individual'?catalog.files:catalog.projects).map(item=><li key={item.file_id??item.project_id} className="flex flex-wrap items-center justify-between gap-3 rounded border p-3"><div className="min-w-0"><p className="break-words">{item.name||'Recovery backup'}</p><time className="text-xs text-muted-foreground" dateTime={item.created_at}>{new Date(item.created_at).toLocaleString()}</time></div><Button variant="outline" disabled={busy} onClick={()=>download(item,kind)}>Download backup</Button></li>)}</ul></section>)}<div className="flex items-center gap-3"><Button variant="outline" disabled={busy||page===1} onClick={()=>setPage(p=>p-1)}>Previous</Button><span>Page {page}</span><Button variant="outline" disabled={busy||!catalog.hasNext} onClick={()=>setPage(p=>p+1)}>Next</Button></div></>}</CardContent></Card></main>;
}
